# This workflow will do a clean install of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: windows-latest
    environment: CI
    steps:
      - uses: DevExpress/testcafe-build-system/actions/prepare@main
        with:
          node-version: 'latest'
      - run: node -v
      - name: Npm install
        run: npm install
      - name: Run Tests
        run: npm run test
